// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 OpenFray contributors

import { describe, expect, it } from 'vitest'
import type { Spell } from '../../src/schema/spell.ts'
import { SPELL_EFFECTS } from '../../src/combat/spellEffects.ts'
import { badgeLabel } from '../../src/combat/effects.ts'

/**
 * What every modelled spell puts on the row, in one readable table. The invariants
 * test proves the *shape* of each entry; this one pins the *wording*, so changing a
 * badge is a visible diff a reviewer can check against the spell text.
 *
 * Columns: key, targeting, the 2024 badge, and the 2014 badge when the editions
 * differ. `(Name)` means the effect carries no note, so the badge is the effect's own
 * name — how every condition is rendered.
 */

const spell = (name: string, edition: '5.0' | '5.5'): Spell => ({
  id: `test:${name}`,
  source: 'test',
  edition,
  name,
  level: 1,
  school: 'Abjuration',
  castingTime: 'action',
  range: 'touch',
  components: { verbal: true, somatic: true, material: false },
  duration: 'up to 1 minute',
  concentration: false,
  ritual: false,
  text: '',
})

/** Badges for one edition, joined with " + " when a spell applies two effects. */
const badges = (key: string, edition: '5.0' | '5.5'): string =>
  SPELL_EFFECTS[key]
    .build({ spell: spell(key, edition) })
    .map((e) => (e.note ? badgeLabel(e) : `(${e.name})`))
    .join(' + ')

type Row = [key: string, targeting: string, badge: string, badge2014?: string]

const EXPECTED: Row[] = [
  ['resistance', 'ally', '+1d4 to a saving throw'],
  ['mage armor', 'ally', 'AC 13 + Dex unarmored'],
  ['protection from evil and good', 'ally', 'Disadv. from listed types'],
  ['sanctuary', 'ally', 'Attackers save or divert'],
  ['shield', 'self', '+5 AC'],
  ['shield of faith', 'ally', '+2 AC'],
  ['aid', 'ally', '+5 HP max & current'],
  ['pass without trace', 'ally', '+10 Stealth'],
  ['protection from poison', 'ally', 'Adv. vs poison; resist'],
  ['warding bond', 'ally', '+1 AC & saves + Shares damage w/ caster'],
  ['beacon of hope', 'ally', 'Adv. Wis & death saves + Healing is maximised'],
  ['magic circle', 'ally', 'Warded from listed types'],
  ['nondetection', 'ally', 'Hidden from divination'],
  ['protection from energy', 'ally', 'Resist chosen damage'],
  ['aura of life', 'ally', 'Resist necrotic (aura)'],
  ['death ward', 'ally', 'Survives one drop to 0'],
  ['freedom of movement', 'ally', 'Ignores grapple/restrain'],
  ['antilife shell', 'self', "Living can't reach you"],
  ['dispel evil and good', 'self', 'Disadv. for listed types'],
  ['contingency', 'self', 'Contingent spell stored'],
  ['globe of invulnerability', 'self', 'Blocks spells ≤ lvl 5'],
  ['antimagic field', 'self', 'No magic within 10 ft'],
  ['holy aura', 'ally', 'Adv. on all saves + Attackers: disadvantage'],
  ['mind blank', 'ally', 'Immune to Psychic & Charmed'],
  ['spirit guardians', 'self', '15 ft aura: half Speed'],
  ['conjure minor elementals', 'self', '+1d8 in the 15 ft aura'],
  ["heroes' feast", 'ally', 'Poison/fear immune; +HP'],
  ['etherealness', 'self', 'On the Ethereal Plane'],
  ['guidance', 'ally', '+1d4 to an ability check'],
  ['comprehend languages', 'self', 'Understands any language'],
  ['detect evil and good', 'self', 'Senses listed types 30 ft'],
  ['detect magic', 'self', 'Senses magic within 30 ft'],
  ['detect poison and disease', 'self', 'Senses poison & disease'],
  ['speak with animals', 'self', 'Can talk with beasts'],
  ['detect thoughts', 'self', 'Reading thoughts'],
  ['locate object', 'self', 'Senses the object'],
  ['see invisibility', 'self', 'Sees invisible & ethereal'],
  ['clairvoyance', 'self', 'Remote sensor active'],
  ['tongues', 'ally', 'Understands any language'],
  ['arcane eye', 'self', 'Invisible eye scouting'],
  ['locate creature', 'self', 'Senses the creature'],
  ['telepathic bond', 'ally', 'Telepathic with the party'],
  ['find the path', 'self', 'Knows the route'],
  ['true seeing', 'ally', 'Truesight 120 ft'],
  ['foresight', 'ally', 'Adv. on all D20 tests + Attackers: disadvantage'],
  ['bless', 'ally', '+1d4 to attacks & saves'],
  ['heroism', 'ally', 'Immune to Frightened'],
  ['glibness', 'self', 'Cha checks count as 15'],
  ['flame blade', 'self', 'Fiery blade in hand'],
  ['spiritual weapon', 'self', 'Spectral weapon out'],
  ['fire shield', 'self', 'Retaliates 2d8; resist'],
  ['arcane hand', 'self', 'Spectral hand active'],
  ['arcane sword', 'self', 'Spectral sword active'],
  ['disguise self', 'self', 'Disguised'],
  ["arcanist's magic aura", 'ally', 'Magic aura masked'],
  ['blur', 'self', 'Attackers: disadvantage'],
  ['invisibility', 'ally', '(Invisible)'],
  ['mirror image', 'self', '3 mirror images'],
  ['greater invisibility', 'ally', '(Invisible)'],
  ['mislead', 'self', '(Invisible) + Illusory double'],
  ['seeming', 'ally', 'Illusory appearance'],
  ['project image', 'self', 'Illusory double elsewhere'],
  ['chantry tithe', 'self', '5 temp HP when others cast'],
  ['vampiric touch', 'self', 'Heals half damage dealt'],
  ['magic jar', 'self', 'Soul in the vessel'],
  ['astral projection', 'ally', 'Astral form (body left)'],
  ['instar', 'self', '20 temp HP & a natural weapon'],
  ['preferment', 'self', 'Advantage on attacks + +20 Speed; 10 temp HP/turn'],
  ['shillelagh', 'self', 'Club uses your spell mod'],
  ['expeditious retreat', 'self', 'Dash as a Bonus Action'],
  ['feather fall', 'ally', 'Falls safely'],
  ['jump', 'ally', 'Jumps 30 ft for 10 ft'],
  ['longstrider', 'ally', '+10 ft Speed'],
  ['alter self', 'self', 'Altered form'],
  ['barkskin', 'ally', 'AC 17 minimum', 'AC 16 minimum'],
  ['darkvision', 'ally', 'Darkvision 150 ft', 'Darkvision 60 ft'],
  ["dragon's breath", 'ally', 'Breath weapon ready'],
  ['enhance ability', 'ally', 'Adv. on chosen ability'],
  ['magic weapon', 'ally', '+1 attack & damage'],
  ['spider climb', 'ally', 'Climbs walls & ceilings'],
  ['blink', 'self', '50%: on the Ethereal'],
  ['fly', 'ally', 'Fly Speed 60, hovers'],
  ['gaseous form', 'ally', 'Gaseous: Fly 10, resist'],
  ['haste', 'ally', '+2 AC & an extra action'],
  ['meld into stone', 'self', 'Melded into stone'],
  ['water breathing', 'ally', 'Breathes underwater'],
  ['water walk', 'ally', 'Walks on liquids'],
  ['stoneskin', 'ally', 'Resist B/P/S', 'Resist nonmagical B/P/S'],
  ['wind walk', 'ally', 'Cloud form: Fly 300 ft'],
  ['regenerate', 'ally', 'Regains 1 HP per turn'],
  ['sequester', 'ally', 'Hidden & unconscious'],
  ['animal shapes', 'ally', 'Beast form'],
  ['shapechange', 'self', 'Shapechanged'],
  ['banishment', 'enemy', '(Incapacitated)'],
  ['resilient sphere', 'enemy', 'Sealed in a force sphere'],
  ['planar binding', 'enemy', 'Bound to service'],
  ['imprisonment', 'enemy', 'Imprisoned'],
  ['ensnaring strike', 'enemy', '(Restrained) + 1d6 piercing/turn'],
  ['entangle', 'enemy', '(Restrained)'],
  ['grease', 'enemy', '(Prone)'],
  ['web', 'enemy', '(Restrained)'],
  ['sleet storm', 'enemy', '(Prone)'],
  ['stinking cloud', 'enemy', '(Poisoned)', 'Retching: loses its action'],
  ['black tentacles', 'enemy', '(Restrained)'],
  ['conjure elemental', 'enemy', '(Restrained)'],
  ['conjure fey', 'enemy', '(Frightened)'],
  ['maze', 'enemy', 'Banished to a maze'],
  ['storm of vengeance', 'enemy', '(Deafened)'],
  ['mind spike', 'enemy', 'Location known to caster'],
  ['scrying', 'enemy', 'Being scried'],
  ['contact other plane', 'self', '(Incapacitated)'],
  ['vicious mockery', 'enemy', 'Disadv. next attack'],
  ['animal friendship', 'enemy', '(Charmed)'],
  ['bane', 'enemy', '−1d4 to attacks & saves'],
  ['charm person', 'enemy', '(Charmed)'],
  ['command', 'enemy', 'Obeys the command'],
  ['hideous laughter', 'enemy', '(Incapacitated) + (Prone)'],
  ['sleep', 'enemy', '(Incapacitated) + Wakes if damaged', '(Unconscious)'],
  ['animal messenger', 'enemy', '(Charmed)'],
  ['calm emotions', 'enemy', 'Calm: charm/fear ended'],
  ['enthrall', 'enemy', 'Disadv. on Perception'],
  ['hold person', 'enemy', '(Paralyzed)'],
  ['suggestion', 'enemy', '(Charmed)'],
  ['zone of truth', 'enemy', "Can't speak a lie"],
  ['charm monster', 'enemy', '(Charmed)'],
  ['compulsion', 'enemy', '(Charmed) + Moved by the caster'],
  ['confusion', 'enemy', 'Confused: rolls 1d10'],
  ['dominate beast', 'enemy', '(Charmed) + Caster commands it'],
  ['dominate person', 'enemy', '(Charmed) + Caster commands it'],
  ['geas', 'enemy', '(Charmed) + 5d10 psychic on refusal'],
  ['hold monster', 'enemy', '(Paralyzed)'],
  ['modify memory', 'enemy', '(Charmed) + (Incapacitated)'],
  ['irresistible dance', 'enemy', '(Charmed) + Dancing: disadv. attacks'],
  ['mass suggestion', 'enemy', '(Charmed)'],
  ['antipathy/sympathy', 'enemy', '(Frightened)'],
  ['befuddlement', 'enemy', 'Int & Cha 1; no spells'],
  ['feeblemind', 'enemy', 'Int & Cha 1; no spells'],
  ['dominate monster', 'enemy', '(Charmed) + Caster commands it'],
  ['power word stun', 'enemy', '(Stunned)'],
  ['faerie fire', 'enemy', 'Attackers: advantage'],
  ['guiding bolt', 'enemy', 'Next attack: advantage'],
  ['sunbeam', 'enemy', '(Blinded)'],
  ['forcecage', 'enemy', 'Caged in force'],
  ['color spray', 'enemy', '(Blinded)'],
  ['phantasmal force', 'enemy', 'Believes the illusion'],
  ['fear', 'enemy', '(Frightened)'],
  ['hypnotic pattern', 'enemy', '(Charmed) + (Incapacitated)'],
  ['phantasmal killer', 'enemy', 'Disadv. checks & attacks', '(Frightened)'],
  ['weird', 'enemy', '(Frightened)'],
  ['ray of enfeeblement', 'enemy', 'Disadv. on Str tests', 'Half damage with Str'],
  ['bestow curse', 'enemy', 'Disadv. chosen ability'],
  ['contagion', 'enemy', '(Poisoned) + Disadv: chosen saves'],
  ['eyebite', 'enemy', '(Frightened)'],
  ['latchwork', 'enemy', 'Disadv. on its next attack'],
  ['blindness/deafness', 'enemy', '(Blinded)'],
  ['enlarge/reduce', 'enemy', 'Size changed: ±1d4 dmg'],
  ['heat metal', 'enemy', 'Drops it or disadvantage'],
  ['levitate', 'enemy', 'Levitating (20 ft up)'],
  ['slow', 'enemy', '−2 AC & Dex saves'],
  ['polymorph', 'enemy', 'Beast form (beast HP)'],
  ['telekinesis', 'enemy', '(Restrained)'],
  ['flesh to stone', 'enemy', '(Restrained) + 3rd fail = Petrified'],
  ['earthquake', 'enemy', '(Prone)'],
  ['true polymorph', 'enemy', 'Transformed'],
  ['hex', 'enemy', '+1d6 necrotic on hits'],
  ["hunter's mark", 'enemy', '+1d6 from the caster'],
  ['divine favor', 'self', '+1d4 radiant on hits'],
  ['searing smite', 'self', '+1d6 fire on the hit'],
  ['branding smite', 'self', '+2d6 radiant on the hit'],
  ['shining smite', 'self', '+2d6 radiant; visible'],
  ['fog cloud', 'enemy', 'Heavily Obscured'],
  ['darkness', 'enemy', 'Magical darkness'],
  ['silence', 'enemy', 'Silenced: no V spells'],
  ['spike growth', 'enemy', 'Spikes: 2d4 per 5 ft'],
  ['cloudkill', 'enemy', 'Heavily Obscured'],
  ['insect plague', 'enemy', 'Lightly Obscured'],
  ['incendiary cloud', 'enemy', 'Heavily Obscured'],
]

describe('spell badge wording', () => {
  it('has a row for every modelled spell', () => {
    expect(EXPECTED.map((r) => r[0]).sort()).toEqual(Object.keys(SPELL_EFFECTS).sort())
  })

  it.each(EXPECTED)('%s → %s', (key, targeting, badge, badge2014) => {
    expect(SPELL_EFFECTS[key].targeting).toBe(targeting)
    expect(badges(key, '5.5')).toBe(badge)
    expect(badges(key, '5.0')).toBe(badge2014 ?? badge)
  })
})
