// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/appendix-a.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

Nineteen encounters from level 1 to level 20. Each leads with the concept it is built around, then gives its terrain and its roster. In this book the terrain is usually the encounter — most of these creatures cannot chase, and the fight only exists because of where it happens.

XP totals are raw sums for budgeting against the 2024 encounter tables. They assume a party of four to five.

#section("The walled kitchen garden")[

]

#encounter(
  name: "",
  levels: "1–2", xp: "300",
  terrain: [60 feet by 40 feet, brick on all four sides, one gate. Raised beds run the length of it in three parallel rows with 2-foot paths between them, so the whole floor is a corridor grid — there is nowhere in this garden that isn’t within 10 feet of something rooted. A cold frame against the north wall gives Half Cover to anyone willing to crouch behind glass. The gate is the only exit and the party came in through it.],
  roster: (
    ("Grinning Gourd", "2", "1/4", "Flanking the central path, one at each end"),
    ("Maize Sentinel", "3", "1/4", "Clustered in the north bed so _Stand of Stalks_ is live"),
    ("Weeping Onion", "2", "1/8", "In the path itself, where they have to be stepped over"),
  ),
  idea: [Nothing here can chase. The fight exists because the party has to cross, and the beds decide where they walk.],
)

#section("The ash field")[

]

#encounter(
  name: "",
  levels: "2–3", xp: "900",
  terrain: [Last year’s crop burned and nobody replanted. Forty acres of black stubble, ankle-deep and crunching, with sightlines in every direction and absolutely no cover — a low stone wall on the far boundary is the only thing to put between yourself and anything. The ground is flat, which matters, because things roll well on it.],
  roster: (
    ("Rollrind", "4", "1", "Scattered in the stubble, motionless, indistinguishable from unburnt pumpkins"),
    ("Emberpod", "2", "1/4", "Rooted at the far boundary, in range of everything"),
  ),
  idea: [Open ground with no cover is usually a gift to a party. Here it’s the problem: the Rollrinds have clear lines and the party has forty acres of nowhere to hide. If someone throws fire into the middle of the group, let the chain reaction happen.],
)

#section("The alarm hedge")[

]

#encounter(
  name: "",
  levels: "2–3", xp: "350",
  terrain: [A cache — a strongbox, a body, a cellar door — sunk in the middle of a hawthorn ring 30 feet across, with a single gap on the east side that has been deliberately planted shut. The hedge is too dense to push through without an axe and too tall to see over. Whatever the plants are rattling _for_ is about four 100 feet north, and it is awake.],
  roster: (
    ("Maize Sentinel", "4", "1/4", "Ringing the cache, spaced so at least three are always in _Stand of Stalks_ range"),
    ("Speartip Row", "3", "1/4", "Filling the planted-shut gap, in _Serried_ formation"),
  ),
  idea: [Killing these is easy. Killing them in under three rounds, quietly, without letting a single _Rustling Alarm_ land, is the encounter. Put a timer on the table.],
)

#section("The buried row")[

]

#encounter(
  name: "",
  levels: "2–3", xp: "300",
  terrain: [A kitchen-garden root bed gone to seed, 30 feet by 20 feet, marked off with a low picket that keeps nothing out. The soil is loose and freshly turned in patches that don’t match any planting pattern a farmer would choose. A well sits at the north end, its cover long since rotted through.],
  roster: (
    ("Snaproot", "4", "1/4", "Buried across the bed in a loose grid, points up"),
    ("Numbknot", "1", "1/2", "Rooted at the well, where the air already runs cold"),
  ),
  idea: [The #cref("c-snaproot", [Snaproot]) patch punishes anyone who moves like there’s nothing underfoot, and the #cref("c-numbknot", [Numbknot]) makes the whole bed slower to cross while they work out why. Nobody here can chase — the only danger is walking through it carelessly.],
)

#section("The quiet acre")[

]

#encounter(
  name: "",
  levels: "3–4", xp: "500",
  terrain: [A ploughed field on a still day. No birds. The furrows are fresh and the soil is turned, so tracks mean nothing and the ground is Difficult Terrain in patches anyway. There is a hedge along the south edge and a scarecrow post in the middle with nothing on it.],
  roster: (
    ("Blightspud", "4", "1/2", "Buried in a rough square, forty feet on a side"),
    ("Podswarm", "1", "1/2", "In the south hedge, waiting for something to disturb the field"),
  ),
  idea: [The party spends the first two rounds looking for something to hit. Tremorsense, a shovel, or an area spell solves it; standing still and squinting does not.],
)

#section("The shed")[

]

#encounter(
  name: "",
  levels: "3–5", xp: "1,250",
  terrain: [A stone potting shed, twenty by fifteen, one door and one shuttered window. Benches down both long walls, tools racked above them, sacks of feed on the floor as Half Cover. It is cramped enough that a Medium creature cannot pass another without squeezing, and everything in it is above head height until it isn’t.],
  roster: (
    ("Animated Shears", "2", "1", "Racked over the left bench"),
    ("Animated Spade", "1", "1", "Against the door frame, digging as soon as the fight starts"),
    ("Animated Hoe", "1", "1", "With the Spade — one knocks down, both hit harder after"),
    ("Animated Scythe", "1", "2", "Hung from the rafters. It goes on round two, not round one"),
  ),
  idea: [A confined room where the party will naturally stand shoulder to shoulder, and a Scythe that punishes exactly that. Describe the tool rack in detail when they walk in. Do not comment on it again.],
)

#section("The bedded field")[

]

#encounter(
  name: "",
  levels: "4–5", xp: "2,250",
  terrain: [A fallow strip behind a ruined farmhouse in late autumn, hoar-frosted and completely still. Three shapes are rooted in a line, dug in for the season, and none of them have moved for weeks. Open ground, good light, the party has all the time they want.],
  roster: (
    ("Stalkstrider", "1", "3", "Bedded down — *Rooted*, Stage 2 statistics"),
    ("Bramblehead", "1", "4", "Bedded down"),
    ("Tearmonger", "1", "2", "Bedded down"),
  ),
  idea: [A free win, and the party should realize it. The encounter is the decision, not the fight: this is the only chance they will ever get at three Stage 2 creatures that cannot move, and it expires at the thaw.],
)

#section("The Scarecrow's circle")[

]

#encounter(
  name: "",
  levels: "5–6", xp: "2,200",
  terrain: [A wheat field gone to seed, waist high, with a single post at the center and a three-100-foot circle of trodden ground around it that nothing else grows in. The wheat is Lightly Obscured above 4 feet and burns extremely well. The field boundary is visible from anywhere in it, which is the point — the party can always see how far they’d have to run.],
  roster: (
    ("Scarecrow", "1", "5", "At the post"),
    ("Bindweed Creeper", "2", "1", "In the trodden ring, where the party will retreat to"),
  ),
  idea: [Two lessons in one field. The #cref("c-scarecrow", [Scarecrow]) will not leave its circle, so withdrawing works — but the Creepers are in the way and cannot be beaten by fighting. And the wheat is dry, and fire is the obvious answer, and fire is how you get a #cref("c-wick", [Wick]).],
)

#section("The broken fence")[

]

#encounter(
  name: "",
  levels: "5–6", xp: "4,500",
  terrain: [A boundary field at dusk. A drystone wall runs the north edge, chest high and climbable; the rest is open pasture with three hay bales for cover and a gate hanging off its hinges to the west. The grass is long enough to hide a rooted thing and short enough that nothing is truly concealed.],
  roster: (
    ("Vinelasher", "1", "4", "On the wall, using the height and its 20-foot reach to pull people off cover"),
    ("Bramblehead", "1", "4", "Center, walking straight at whoever is heaviest"),
    ("Stalkstrider", "2", "3", "Working as a pair, cutting the field in half with _Sow the Row_"),
    ("Tearmonger", "2", "2", "Rear, shedding onions as they take hits"),
  ),
  idea: [The Stalkstriders will split the party in two and the #cref("c-vinelasher", [Vinelasher]) will pull one half apart. Fire is the answer and the party will find it.],
)

#section("The ley bottom")[

]

#encounter(
  name: "",
  levels: "6–8", xp: "3,500",
  terrain: [A hollow where three fields meet and the water never drains. Standing water ankle to knee deep across the whole floor, reeds high enough to break line of sight, and a persistent wrongness — compass needles drift, and it is colder here in summer than it should be. The only dry ground is a raised causeway running east to west, 5 feet wide.],
  roster: (
    ("Chimeweed", "3", "1", "Rooted along the causeway, so the dry route is also the silent one"),
    ("Drownbulb", "1", "4", "In the deepest water, blocking the eastern exit"),
    ("Fondvine", "1", "5", "In the reeds, out of sight, working"),
  ),
  idea: [The caster’s spells fail on the only footing that isn’t waist-deep water, the exit is held by something that takes their air, and somewhere in the reeds a party member is being quietly turned around. This is the encounter to run when a party has got comfortable.],
)

#section("The frostbite hollow")[

]

#encounter(
  name: "",
  levels: "6–7", xp: "4,700",
  terrain: [A dip in the land where cold pools on even the warmest day, hedged in by dead brambles that never quite finished dying. The ground frosts white past the treeline and stays that way. A footpath cuts straight through the middle — the fast way across, and the wrong one.],
  roster: (
    ("Rootlance", "1", "4", "Planted at the mouth of the path, waiting for someone to run"),
    ("Gingerling", "2", "5", "Circling wide, using the hedges for cover, never standing still"),
  ),
  idea: [The #cref("c-rootlance", [Rootlance]) wants the party to charge the path and the Gingerlings want them to chase it off the path. Both instincts are wrong. This is the encounter where standing still and letting the enemy come to you is the correct, unfamiliar answer.],
)

#section("The drill ground")[

]

#encounter(
  name: "",
  levels: "7–8", xp: "5,100",
  terrain: [A long level strip that was clearly laid out on purpose — turf cropped short, edges squared, a mounting block at one end. Two 100 feet by 60 feet, no cover anywhere on it, and a treeline 40 feet off the western edge that the party will want and will not be allowed to reach.],
  roster: (
    ("Pikeling", "4", "3", "A block of four in _Formation_, holding the center"),
    ("Scorchvine", "1", "6", "Flanking wide and fast around the block"),
  ),
  idea: [The Pikelings hold and the #cref("c-scorchvine", [Scorchvine]) goes around. Charging the block is the wrong answer and _Set Against the Charge_ will explain why. Somebody taught them this, and the party should end the fight asking who.],
)

#section("The sunken field")[

]

#encounter(
  name: "",
  levels: "8–9", xp: "5,400",
  terrain: [A waterlogged bottom field below the level of everything around it, reached down a muddy bank. Difficult Terrain across the whole floor, standing water in the ruts, and a drainage ditch running its length that a Large creature can lie down in. The banks are steep enough that leaving is a climb.],
  roster: (
    ("Hollowman", "1", "5", "Below ground, surfacing and submerging, never where it was"),
    ("Tanglepod", "2", "5", "Holding the bank, stopping anyone reaching whoever gets dragged under"),
  ),
  idea: [_Drag Under_ takes a character out of the fight and the Tanglepods make rescuing them expensive. The party has to choose between the person and the problem.],
)

#section("The garden wall")[

]

#encounter(
  name: "",
  levels: "8–10", xp: "8,300",
  terrain: [A walled kitchen garden gone feral, four acres inside 8-foot brick, espaliered fruit still pinned to the south face. Gravel paths in a formal cross, box hedging waist high, a glasshouse along one wall with most of its panes gone. Every path is a sightline and every hedge is a place to be on the wrong side of.],
  roster: (
    ("Gardener", "1", "8", "Somewhere with a plant within five feet of it, which is everywhere"),
    ("Under-Gardener", "1", "5", "Opposite corner"),
    ("Pruneling", "4", "1/2", "Hidden, going for packs and components"),
    ("Bramblehead", "2", "4", "Slow, in the way, buffed by _Tender of the Plot_"),
  ),
  idea: [Two _Patient_ creatures, one of which can walk the line on its first turn. Roll both initiatives with Disadvantage in the open so the party sees it happen and does not know why yet. The #cref("c-gardener", [Gardener]) will talk first if allowed.],
)

#section("The crowned acre")[

]

#encounter(
  name: "",
  levels: "10–12", xp: "8,900",
  terrain: [A field of maize 12 feet high that has not been harvested in three years, rows still faintly visible, a mile square. Heavily Obscured almost everywhere. There is a wagon track through the middle that offers the only reliable sightline, and taking it is the obvious move and the wrong one.],
  roster: (
    ("Harvest Crown", "1", "11", "Anywhere. It will find them"),
    ("Maize Sentinel", "6", "1/4", "Rooted through the rows, invisible until 15 feet"),
    ("Stalkstrider", "2", "3", "Walking the wagon track"),
  ),
  idea: [The party cannot see, cannot move at speed, and cannot avoid the Sentinels because they will not know they are there. Fire solves the field and lights up everything in it, including them.],
)

#section("The deep furrow")[

]

#encounter(
  name: "",
  levels: "11–13", xp: "7,400",
  terrain: [A single vast taproot has cracked a hillside field into a star-shaped web of 30-foot fissures, radiating out from a point the party can’t yet see. The soil beyond each crack is Difficult Terrain, and the whole hillside knows they’re standing on it before they do.],
  roster: (
    ("Deepspire", "1", "11", "At the center of the star, mostly underground"),
    ("Snaproot", "4", "1/4", "Scattered along the fissures, part of the same root system"),
  ),
  idea: [Spire of Roots means the #cref("c-deepspire", [Deepspire]) always knows exactly where the party is within thirty feet, seen or not. The Snaproots aren’t separate creatures so much as extensions of it — killing them doesn’t slow it down, but ignoring them costs blood with every step. Early rounds favor the party if they can keep it moving; once the crown snaps, standing still stops being an option for it and starts being the only option for them.],
)

#section("The churchyard siege")[

]

#encounter(
  name: "",
  levels: "12–14", xp: "13,500",
  terrain: [A walled graveyard on a hillside, two acres, yews and leaning stones. The wall is 4 feet and easily crossed. The ground is half open graves — Difficult Terrain and worse, since things are coming out of them. At the center, a garlic tree 40 feet across has grown up through the chapel foundations, and it is losing.],
  roster: (
    ("Reliquary", "1", "12", "Center, holding, at roughly half Hit Points when the party arrives"),
    ("Blight Mother", "1", "7", "Uphill, behind the yews, raising everything that falls"),
    ("Gravegourd", "2", "4", "Working the flanks"),
  ),
  idea: [The party arrives mid-fight beside a CR 12 ally that will not ask for help and will cast _Litany_ on them whether they help or not. Every plant that dies here gets back up, including the #cref("c-reliquary", [Reliquary])’s own defenders, so killing things is actively counterproductive until the #cref("c-blight-mother", [Blight Mother]) is down.],
)

#section("The long winter")[

]

#encounter(
  name: "",
  levels: "13–15", xp: "13,600",
  terrain: [The cold end of a field that shouldn’t have one — frost inward from a boundary hedge that gets thicker every year, air so still that breath hangs in it. At the center, the ground has stopped supporting anything but itself. Nothing here has moved quickly in a long time.],
  roster: (
    ("Torpor", "1", "13", "Center, patient, already aware they’ve arrived"),
    ("Gingerling", "2", "5", "Raised fresh from the soil as the fight goes on, not present at the start"),
  ),
  idea: [#cref("c-torpor", [Torpor]) doesn’t need to catch anyone — Creeping Numbness does that for it, and Rhizome Sovereign means the two Gingerlings on the table at the start won’t be the last. The party’s instinct will be to disengage and regroup at range; Deep Winter means Torpor’s Speed can’t be slowed in return, so the gap never actually opens. The fight rewards standing and finishing it, not managing distance.],
)

#section("The last valley")[

]

#encounter(
  name: "",
  levels: "18–20", xp: "63,200",
  terrain: [A shallow valley eight miles from anywhere, terraced by no one, every terrace under cultivation. The floor is a mile of tilled soil and the sides are stepped beds rising two 100 feet. There is one way in and it is downhill. Nothing here is wild and nothing here was planted by a person.],
  roster: (
    ("Perennial", "1", "22", "Center floor, already aware, already talking"),
    ("Harvest Crown", "1", "11", "Upper terrace, under _Sovereign of the Soil_"),
    ("Green Multitude", "1", "16", "Lower terrace, same"),
  ),
  idea: [The Rend numbers are not the threat. _Sovereign of the Soil_ is: two Stage 3 creatures with Advantage and +6 damage, and *Call the Beds* every other round replacing whatever the party clears. Fight the field or lose to it.],
)
