// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/chapter-3.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

A plant that has taken more from the soil than the soil was meant to give tears itself free, trailing a taproot it will never fully shed. It walks badly and it does not sleep.

Stage 2 creatures are ambush predators in cultivated land, and territorial toward each other — which is why parties rarely meet more than two or three of the same species together.

Any Stage 2 creature can be found *bedded down*: rooted for a season in order to advance, using the *Rooted* trait from Chapter 2 while keeping all its Stage 2 statistics. That is the most vulnerable it will ever be, and the best opportunity a party will ever get to kill something before it becomes a problem.

#show-creature("Gourdstalker")

#show-creature("Gravegourd")

#show-creature("Tearmonger")

#show-creature("Drownbulb")

#show-creature("Stalkstrider")

#show-creature("Bramblehead")

#show-creature("Tumblewrack")

#show-creature("Vinelasher")

#show-creature("Fondvine")

#show-creature("Hollowman")

#show-creature("Censerhead")

#show-creature("Scorchvine")

#show-creature("Pikeling")

#show-creature("Tanglepod")

#show-creature("Rootlance")

#show-creature("Gingerling")
