// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/chapter-7.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

_The First Furrow. Mother Root. The thing every garden is a cutting from._

Every plant in this book is descended from it, and most of them are literally _of_ it — a #cref("c-pumpkin-king", [Pumpkin King]) is a bud that got away, a #cref("c-harvest-crown", [Harvest Crown]) is a severed runner that took. The #cref("c-perennial", [Perennial]) has been in the ground since before the ground was farmed, and it has been patiently teaching the world to cultivate itself ever since. Gardens are not something people do to it. Gardens are how it spreads.

It does not need to be met. That’s the point of it. But if you want one encounter that recontextualizes the entire book, this is it: the party walks into a valley and finds every species they have ever fought grafted into a single body, and the body knows their names, because it has been watching through every stem they ever cut.

#pagebreak(weak: true)

#section-head("Regional Effects")

Within 6 miles of the Perennial:

- Every garden, field, allotment, and window box produces at least one waking plant per season. Nobody local finds this remarkable any more.
- All plants — ordinary and otherwise — turn to face the Perennial’s valley at dawn, regardless of where the sun is.
- Anyone who eats produce grown in the region dreams of being buried, and finds it deeply comforting.
- Plant creatures within the area can’t be Charmed, commanded, turned, or spoken to by any effect that isn’t the Perennial’s. _Speak with plants_ returns only one voice, and it is not the plant’s.

If the Perennial is ended for good, these fade over a full year — one season at a time, in reverse.

#colbreak(weak: true)

#show-creature("Perennial")

#section("Running the Perennial")[
*It should not be a surprise.* By the time a party fights this, they should have killed at least two Stage 3 bosses and noticed that each one had a scar where something was cut away from it. The Grafts table is the payoff: every ability it uses is one they have already survived, stitched onto something ten times larger.

*Announce the Graft out loud.* “The trunk swells and the bark blackens — you know that color” lands much harder than rolling a d10 in secret. Let the party recognize the Pumpkin King’s fire and the Harvest Crown’s obscuring rows on the same body. The recognition _is_ the encounter.

*It isn’t malicious.* Neutral alignment is deliberate. The Perennial has no grievance against anyone; it is doing agriculture at a scale where people are a soil amendment. It will talk, at length, and it is genuinely curious about what the party thinks it should do instead. Nothing they say will change anything.

*On CR 22 with a party of five level-18 characters:* this is a hard fight, not a lethal one, and it’s meant to be run in a valley with the Beds actively spawning. If you want it to be genuinely deadly at level 20, run it with two Stage 3 creatures already on the board and let _Sovereign of the Soil_ give them Advantage and +6 damage — that trait is where the real threat lives, not in the Rend numbers.

*The seed.* Whatever happens, someone should end the session holding it. It is warm.
]
