// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/chapter-6.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

Chapter 1 lists _deliberate cultivation_ as the most interesting reason a plant advances. This chapter is who has been doing it.

Everything here either works for the #cref("c-gardener", [Gardener]) or has been drawn in by it, and unlike most of Chapter 5, all of it will come at the party. One entry is deliberately non-lethal: the #cref("c-tithe-crow", [*Tithe-Crow*]) doesn’t want to kill anyone, it wants something they’re carrying, and it will trade.

The Gardener’s _animate objects_ results are statted as six separate implements rather than one entry with a table, because a hose and a pair of shears are not the same creature.

*Run the #cref("c-under-gardener", [Under-Gardener]) before the Gardener.* They share the _Patient_ trait, and the lieutenant’s version is stripped down enough that a party can learn the mechanic from a fight that costs them Hit Points instead of a character.

#show-creature("Pruneling")

#pagebreak(weak: true)

#section("Animated tools")[
The Gardener casts _animate objects_ on whatever is leaning against the shed wall. Six of those results are statted below, so nobody has to open the generic animated-object rules mid-fight.

All six are built on the same chassis — the same _Antimagic Susceptibility_, the same _False Appearance_, both printed in full on each block — and differ entirely in what they do with it.

The composition of a tool encounter should be a piece of scenery the party walked past ten minutes earlier. Let them notice the rack. Let them do nothing about it.

#data-table(
  columns: 3,
  aligns: (left, center, left),
  head: ("Tool", "CR", "Does"),
  rows: (
    [#align(left)[Animated Shears]], [#align(center)[1]], [#align(left)[Strips gear off people]],
    [#align(left)[Animated Spade]], [#align(center)[1]], [#align(left)[Digs pits, knocks people into them]],
    [#align(left)[Animated Hoe]], [#align(center)[1]], [#align(left)[Wrecks the ground, punishes the Prone]],
    [#align(left)[Animated Watering Can]], [#align(center)[1]], [#align(left)[Support. Heals other plants]],
    [#align(left)[Animated Scythe]], [#align(center)[2]], [#align(left)[Reach, sweeps two targets at once]],
    [#align(left)[Animated Hose]], [#align(center)[3]], [#align(left)[Long-range grapple, pins, drowns]],
  ),
)
]

#show-creature("Animated Shears")

#show-creature("Animated Spade")

#show-creature("Animated Hoe")

#show-creature("Animated Watering Can")

#show-creature("Animated Scythe")

#show-creature("Animated Hose")

#show-creature("Tithe-Crow")

#show-creature("Rookery Choir")

#show-creature("Under-Gardener")

#show-creature("Gallows Rook")

#show-creature("Gardener")
