// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/chapter-4.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

A Stage 3 plant is not an encounter that happened to be in the way. It took years, and something fed it for years. The interesting question is who let it get that big, and why nobody in the nearest village will talk about it.

- *They are solitary.* A crowned plant starves everything around it. Expect a wide ring of stunted, dying Stage 1 plants and no Stage 2 at all within a mile — it ate them.
- *They are aware.* Every Stage 3 has an Intelligence high enough to negotiate, and most can speak. An eleven-foot vegetable that opens with a reasonable-sounding offer is more memorable than one that rolls initiative.
- *They cannot be harvested.* The taproot goes down forty feet. Killing one does not clear the soil; the bed produces Stage 1 growth again within a season unless it’s salted.

Each of these is a legendary creature with regional or field-scale effects, and each is built around one idea a party has to solve rather than out-damage. Treat any Stage 3 as the centerpiece of a session.

#show-creature("Lachrymose")

#show-creature("Thistle Colossus")

#show-creature("Harvest Crown")

#show-creature("Reliquary")

#show-creature("Bloodvine Sovereign")

#section-head("Regional Effects")

Within 1 mile of the King’s field:

- Vegetables grow malformed faces and are inedible. Farmers who eat them dream of orange light.
- Livestock refuse to enter the fields and will break a fence to avoid it.
- Dusk holds for an extra hour, the light staying low and orange well past true sunset.
- Travelers who leave the field at night find themselves walking back toward it. A DC 16 Wisdom (Survival) check each hour is needed to make genuine progress away.

If the King dies, these fade over 1d10 days.

#show-creature("Pumpkin King")

#show-creature("Serried Crown")

#show-creature("Long Root")

#show-creature("Scald")

#show-creature("Green Multitude")

#show-creature("Deepspire")

#show-creature("Torpor")

#wide[
  #text(size: 12.5pt, weight: 800, fill: accent-deep)[Which boss to use]
  #hrule()
#table(
  columns: 3,
  inset: (x: 3pt, y: 2.4pt),
  stroke: (x, y) => (bottom: 0.5pt + rule-col),
  table.header(align(left)[#label-head("Boss")], align(center)[#label-head("CR")], align(left)[#label-head("What the fight is about")]),
  [#align(left)[Lachrymose]], [#align(center)[9]], [#align(left)[Fighting blind, and the adds it keeps shedding]],
  [#align(left)[Thistle Colossus]], [#align(center)[10]], [#align(left)[Grinding three health bars while it Grapples the squishiest character]],
  [#align(left)[Deepspire]], [#align(center)[11]], [#align(left)[You cannot reach most of it, and it hits harder once its crown snaps]],
  [#align(left)[Harvest Crown]], [#align(center)[11]], [#align(left)[Terrain. The party cannot see, cannot move, must solve it with fire]],
  [#align(left)[Bloodvine Sovereign]], [#align(center)[12]], [#align(left)[Artillery from a creature that gets stronger every time anything dies]],
  [#align(left)[Reliquary]], [#align(center)[12]], [#align(left)[Probably not a fight. An ally that wants something]],
  [#align(left)[Serried Crown]], [#align(center)[13]], [#align(left)[An army, not a creature. Reach and infantry]],
  [#align(left)[Torpor]], [#align(center)[13]], [#align(left)[Slows the whole field and raises a fresh Gingerling every round]],
  [#align(left)[Pumpkin King]], [#align(center)[14]], [#align(left)[Talks first, commands the field, second phase when Bloodied]],
  [#align(left)[Scald]], [#align(center)[15]], [#align(left)[Speed and burst. Fire heals it — the reversal]],
  [#align(left)[Green Multitude]], [#align(center)[16]], [#align(left)[Hitting it makes more of it]],
  [#align(left)[Long Root]], [#align(center)[16]], [#align(left)[A puzzle. You cannot hit what you can see]],
)
]
