// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/chapter-1.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

Before the creatures, the ground they came out of. This chapter covers how a plant wakes and advances, the five kinds of ground that produce something other than the usual, what a party can read off a field before they step into it, and what they can take home afterwards.

#section("The growth cycle")[
Which stage a party encounters is a fact about the _place_, not about the fight.

#table(
  columns: 4,
  inset: (x: 3pt, y: 2.4pt),
  stroke: (x, y) => (bottom: 0.5pt + rule-col),
  table.header(align(left)[#label-head("Stage")], align(left)[#label-head("Form")], align(left)[#label-head("Typical CR")], align(left)[#label-head("Tier of play")]),
  [#align(left)[*1 — Rooted*]], [#align(left)[Awake, aware, immobile]], [#align(left)[1/8 – 1/2]], [#align(left)[Levels 1–3]],
  [#align(left)[*2 — Uprooted*]], [#align(left)[Tears free, walks, hunts]], [#align(left)[2 – 6]], [#align(left)[Levels 4–8]],
  [#align(left)[*3 — Crowned*]], [#align(left)[Enormous, territorial, sovereign]], [#align(left)[9 – 16]], [#align(left)[Levels 9+]],
)
]

#section-head("What drives advancement")
Left in ordinary loam, a Stage 1 plant stays Stage 1 indefinitely — it will sit in that furrow and hiss at passers-by for fifty years. Advancement requires one of:

- *Season and surplus.* Roughly one growing season per stage in genuinely rich soil. Slow and boring, which is how a neglected estate garden ends up dangerous.
- *Interment.* Something was buried there. A battlefield, a plague pit, a single powerful corpse. The most common cause, and the most useful, because it comes with a reason the party is already investigating.
- *Ambient magic.* A ley line, a wild magic scar, a druid’s failed working, a wizard’s leaking laboratory drain.
- *Deliberate cultivation.* Somebody is _farming_ these. The most interesting version, and the one that gives you an antagonist.

#section-head("What arrests it")
- *Harvesting* removes a plant permanently.
- *Salting the bed* prevents any further advancement in that soil for a year.
- *Hard frost* knocks a plant back a stage if it’s caught rooted.
- *Crowding.* A patch that grows too dense starves itself. Stage 3 specimens are almost always solitary, surrounded by a dead zone of stunted plants that never got their share.

#section-head("Bedding down")
A Stage 2 creature that wants to advance must root itself again and hold still for a season — the most vulnerable thing it will ever do. A bedded-down Stage 2 uses the *Rooted* trait but keeps its Stage 2 statistics otherwise. This is the best opportunity a party will ever get to kill something before it becomes a problem.

#section("The soil")[
Soil determines more than size. Two gourds from the same seed, grown forty feet apart, can be entirely different problems — and the ground tells you which one you’re about to meet before it moves.

There are no modifiers here and nothing to recalculate. Bad ground produces a _different creature_, and those creatures have their own stat blocks.

*Ash ground.* Burned-over fields, charcoal pits, the site of an old fire. Rinds come out dry, brittle, and full of gas. Ash ground produces things that move when they shouldn’t and come apart on purpose — the #cref("c-rollrind", [*Rollrind*]) and the #cref("c-tumblewrack", [*Tumblewrack*]).

*Grave ground.* A battlefield, a plague pit, one powerful corpse. What grows here knows the names of what’s under it and is not shy about using them. See the #cref("c-gravegourd", [*Gravegourd*]).

*Ley ground.* A ley line, a wild magic scar, a druid’s failed working, a wizard’s leaking drain. Growth here comes out wrong in ways that have nothing to do with strength: the #cref("c-chimeweed", [*Chimeweed*]) silences, the #cref("c-fondvine", [*Fondvine*]) makes people love it. Ley ground is where a garden stops being a fight and starts being a problem.

*Bog ground.* Waterlogged bottom fields and drainage ditches. Slow, heavy, foul, and much harder to kill than it looks. See the #cref("c-drownbulb", [*Drownbulb*]).

*Starved ground.* The dead ring around anything crowned. Too many plants, not enough soil, nothing gets its share. What survives is small, numerous, and desperate — the #cref("c-runt-patch", [*Runt Patch*]).

To add a variety that isn’t in this book, write it as a new creature with its own name. Don’t adjust an existing creature’s numbers. Give it different traits instead — that is what makes a variety worth running.
]

#section("Reading the bed")[
A party that looks before it walks can tell which stage is in the field, and often what kind of ground grew it. Each sign below is a single check made from the edge of the bed — on a success, tell them the right-hand column.

#table(
  columns: 3,
  inset: (x: 3pt, y: 2.4pt),
  stroke: (x, y) => (bottom: 0.5pt + rule-col),
  table.header(align(left)[#label-head("Sign")], align(left)[#label-head("DC (Nature or Survival)")], align(left)[#label-head("Tells them")]),
  [#align(left)[Furrows disturbed from beneath, no tracks leading away]], [#align(left)[10]], [#align(left)[Stage 1 present]],
  [#align(left)[Drag-marks: a broad trailing groove between prints]], [#align(left)[13]], [#align(left)[Stage 2 active]],
  [#align(left)[Wide dead zone, stunted plants, soil gray and depleted]], [#align(left)[15]], [#align(left)[Stage 3 nearby, and it has been here years]],
  [#align(left)[Scorched hardpan, rinds cracked and weeping sap]], [#align(left)[13]], [#align(left)[Ash ground — expect things that roll, do not melee]],
  [#align(left)[Soil that smells of iron; bone fragments turned by the plough]], [#align(left)[14]], [#align(left)[Grave ground]],
  [#align(left)[Compass needles drifting; frost in summer, dew in drought]], [#align(left)[15]], [#align(left)[Ley ground]],
  [#align(left)[Total birdsong silence over a cultivated field]], [#align(left)[14]], [#align(left)[Something is hunting here now]],
)
]

#section("Harvesting")[
A creature within 5 feet of any Stage 1 or Stage 2 plant at 0 Hit Points can take an action, with an Herbalism Kit or sickle, to make a *DC 13 Wisdom (Medicine) or Intelligence (Nature) check* — DC 16 for Stage 2 — to sever the taproot cleanly. Stage 3 plants cannot be harvested.

- *Success:* permanently harvested, yields 1 usable component.
- *Failure by 4 or less:* dead, but the component is ruined.
- *Failure by 5 or more:* the taproot retracts into the soil and regrows at half its Hit Point maximum within 30 feet, after 1 minute at Stage 1 or 1 hour at Stage 2.

#table(
  columns: 3,
  inset: (x: 3pt, y: 2.4pt),
  stroke: (x, y) => (bottom: 0.5pt + rule-col),
  table.header(align(left)[#label-head("Species")], align(left)[#label-head("Component")], align(left)[#label-head("Suggested use")]),
  [#align(left)[Pumpkin]], [#align(left)[Ember seed]], [#align(left)[1 flask alchemist’s fire; 3 from a Gourdstalker]],
  [#align(left)[Onion]], [#align(left)[Bitter tear]], [#align(left)[Antitoxin, or 1 dose of blinding powder]],
  [#align(left)[Maize]], [#align(left)[Whisper husk]], [#align(left)[Casts _alarm_ without material cost]],
  [#align(left)[Cabbage]], [#align(left)[Layered heart]], [#align(left)[Restores 1 Hit Die on a Short Rest]],
  [#align(left)[Tomato]], [#align(left)[Caustic fruit]], [#align(left)[Improvised grenade: 2d6 Acid, 5-ft radius, DC 12 Dex]],
  [#align(left)[Potato]], [#align(left)[Black eye]], [#align(left)[Poison that reduces Hit Point maximum (DC 12 Con, 2d6)]],
  [#align(left)[Garlic]], [#align(left)[Blessed clove]], [#align(left)[Undead have Disadvantage on attacks against the holder for 1 hour]],
  [#align(left)[Chili]], [#align(left)[Ember pip]], [#align(left)[Adds 1d4 Fire damage to a weapon for 10 minutes]],
  [#align(left)[Asparagus]], [#align(left)[Spear frond]], [#align(left)[Improvised spear, +1 damage against charging creatures]],
  [#align(left)[Pea]], [#align(left)[Rattle pod]], [#align(left)[Thrown: 10-ft area of Difficult Terrain for 1 minute]],
  [#align(left)[Carrot]], [#align(left)[Snapped point]], [#align(left)[Improvised piercing weapon, +1 to hit while it lasts (1 hour)]],
  [#align(left)[Ginger]], [#align(left)[Numbing root]], [#align(left)[Chewed: Advantage on the next Constitution saving throw against poison, within 10 minutes]],
)

An ash-grown plant’s component always detonates for 2d6 Fire if the harvester fails the check by any margin.
]
