// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/chapter-2.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

Awake, aware, and unable to leave. A Stage 1 plant will sit in its furrow for fifty years if the soil never gives it more than it needs.

Nearly every Stage 1 creature has the *Rooted* trait, printed in full on each stat block that carries it: its Speed is 0 and can’t be increased, and it can’t be moved against its will or have the Prone condition imposed on it while it has more than 0 Hit Points.

The exceptions are the *Rollrind* and the *Podswarm*, which move freely, and the *Runt Patch*, which drags its roots along behind it.

Before running these, read Stage 1 and challenge rating. It matters more than the numbers do.

#show-creature("Grinning Gourd")

#show-creature("Rollrind")

#show-creature("Weeping Onion")

#show-creature("Maize Sentinel")

#show-creature("Chimeweed")

#show-creature("Thistleheart Cabbage")

#show-creature("Bloodvine Tomato")

#show-creature("Blightspud")

#show-creature("Wardbulb")

#show-creature("Emberpod")

#show-creature("Speartip Row")

#show-creature("Podswarm")

#show-creature("Snaproot")

#show-creature("Numbknot")

#show-creature("Runt Patch")
