// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/chapter-5.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

Not everything in a cultivated plot is a vegetable. Weeds, pests, rot, and the things that keep them in check are all part of the same ecology, and a garden strange enough to grow a #cref("c-pumpkin-king", [Pumpkin King]) grows strange versions of these too.

None of these are staged. They don’t advance, they don’t bed down, they don’t produce a crowned form. They’re the standing population of a special garden, and they exist to make encounters feel like an ecosystem rather than a creature list.

Several of them are not the party’s problem at all. The #cref("c-aphid-bloom", [*Aphid Bloom*]) drains plants and heals off them. The #cref("c-shearbeetle", [*Shearbeetle*]) will always attack a vegetable over a person. The #cref("c-compost-shambler", [*Compost Shambler*]) collapses into soil that heals every plant standing in it. Dropping one of these into a bed produces a three-way fight the party can watch, exploit, or tip — and that is usually a better scene than another wave of enemies.

For creatures that come at the party directly, see Chapter 6.

#show-creature("Gloamsnail")

#show-creature("Shellmaw")

#show-creature("Aphid Bloom")

#show-creature("Bindweed Creeper")

#show-creature("Sting-Choir")

#show-creature("Compost Shambler")

#show-creature("Scarecrow")

#show-creature("Wick")

#show-creature("Shearbeetle")

#show-creature("Blight Mother")

#show-creature("Hive-Warden")
