// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/overview.mdx — do not edit.
// Placed by print/waking-garden.typ.
#import "../lib.typ": *

#wide[
  #wide-head("Index by species")
  #set text(size: t-index)
The ten cultivated species, each across all three stages. The number after each creature is its challenge rating.

#data-table(
  columns: 4,
  aligns: (left, left, left, left),
  head: ("Species", "Stage 1", "Stage 2", "Stage 3"),
  rows: (
    [#align(left)[Pumpkin]], [#align(left)[Grinning Gourd (1/4)]], [#align(left)[Gourdstalker (3)]], [#align(left)[Pumpkin King (14)]],
    [#align(left)[Onion]], [#align(left)[Weeping Onion (1/8)]], [#align(left)[Tearmonger (2)]], [#align(left)[Lachrymose (9)]],
    [#align(left)[Maize]], [#align(left)[Maize Sentinel (1/4)]], [#align(left)[Stalkstrider (3)]], [#align(left)[Harvest Crown (11)]],
    [#align(left)[Cabbage]], [#align(left)[Thistleheart Cabbage (1/4)]], [#align(left)[Bramblehead (4)]], [#align(left)[Thistle Colossus (10)]],
    [#align(left)[Tomato]], [#align(left)[Bloodvine Tomato (1/2)]], [#align(left)[Vinelasher (4)]], [#align(left)[Bloodvine Sovereign (12)]],
    [#align(left)[Potato]], [#align(left)[Blightspud (1/2)]], [#align(left)[Hollowman (5)]], [#align(left)[Long Root (16)]],
    [#align(left)[Garlic]], [#align(left)[Wardbulb (1/4)]], [#align(left)[Censerhead (4)]], [#align(left)[Reliquary (12)]],
    [#align(left)[Chili]], [#align(left)[Emberpod (1/4)]], [#align(left)[Scorchvine (6)]], [#align(left)[Scald (15)]],
    [#align(left)[Asparagus]], [#align(left)[Speartip Row (1/4)]], [#align(left)[Pikeling (3)]], [#align(left)[Serried Crown (13)]],
    [#align(left)[Pea]], [#align(left)[Podswarm (1/2)]], [#align(left)[Tanglepod (5)]], [#align(left)[Green Multitude (16)]],
    [#align(left)[Carrot]], [#align(left)[Snaproot (1/4)]], [#align(left)[Rootlance (4)]], [#align(left)[Deepspire (11)]],
    [#align(left)[Ginger]], [#align(left)[Numbknot (1/2)]], [#align(left)[Gingerling (5)]], [#align(left)[Torpor (13)]],
  ),
)

*Variants* are their own creatures, not modifiers: #cref("c-rollrind", [Rollrind]) (1), #cref("c-chimeweed", [Chimeweed]) (1), The #cref("c-runt-patch", [Runt Patch]) (1), #cref("c-drownbulb", [Drownbulb]) (4), #cref("c-gravegourd", [Gravegourd]) (4), #cref("c-fondvine", [Fondvine]) (5), #cref("c-tumblewrack", [Tumblewrack]) (3). See _The Soil_ in Chapter 1 for which ground produces what.
]
