// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/licensing.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *


