// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/overview.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

_A bestiary of cultivated horrors, compatible with 5e and 5.5e_

Sixty-seven creatures for a world where the things people grow have started growing back. Twelve species of sentient vegetable across three stages of life, the ecology that lives alongside them, the fey who tend them, and the thing they are all cuttings from.

Every stat block is compatible with 5.5e and 5e. It is tuned mainly for the power level of 5.5e, so some creatures may feel stronger than their listed challenge rating in a 5e game.

Use as much of it as you want. A single creature is a roadside encounter. One stage is a set of random encounters for a tier of play. A group of them is a one-shot. All three stages, in order, is a campaign.

#section("What's in each chapter")[
*Chapter 1* is the setting: how these plants grow, what makes them dangerous, and what a party can tell by looking at the dirt. It’s short, and it makes everything after it make sense. Read it first.

*Chapters 2–4* are the cultivated plants, arranged by stage of life. A plant does not change stage during a fight — it changes over seasons. Which stage a party meets is a fact about the _place_.

*Chapter 5* is everything else that lives in a garden. Weeds, pests, rot, and the things that keep them down. Several of these would rather eat a vegetable than a person.

*Chapter 6* is the answer to who has been doing all this on purpose.

*Chapter 7* is the answer to why any of it woke up in the first place.

*Appendix A* has nineteen ready-to-run encounters from level 1 to level 20, each with its terrain, its roster, and the concept it’s built around.
]

#section-head("Stage 1 and challenge rating")
A creature with Speed 0 is a hazard, not an encounter. Players will walk around it, and they’re right to. Every Stage 1 creature in Chapter 2 earns its listed challenge rating only when one of these is true:

- *Terrain forces contact.* A walled kitchen garden, a greenhouse, a hedge maze, furrows narrow enough that a 10-foot reach covers the path.
- *The plants are the objective.* The party needs them harvested, cleared, or taken alive.
- *They’re guarding something.* A Stage 1 patch around a cache is a cheap, patient alarm that never sleeps and can’t be bribed.
- *They’re supporting something mobile.* One Stalkstrider among four rooted Maize Sentinels is a better fight than either alone.

In open ground with no clock, halve their effective challenge rating. The ash-grown plants are the exception, because they move.

#section("Index by challenge rating")[
#table(
  columns: 5,
  inset: (x: 3pt, y: 2.4pt),
  stroke: (x, y) => (bottom: 0.5pt + rule-col),
  table.header(align(center)[#label-head("CR")], align(right)[#label-head("XP")], align(left)[#label-head("Creature")], align(left)[#label-head("Type")], align(left)[#label-head("Ch.")]),
  [#align(center)[0]], [#align(right)[10]], [#align(left)[Gloamsnail]], [#align(left)[Beast]], [#align(left)[Ch. 5]],
  [#align(center)[1/8]], [#align(right)[25]], [#align(left)[Weeping Onion]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/4]], [#align(right)[50]], [#align(left)[Aphid Bloom]], [#align(left)[Beast]], [#align(left)[Ch. 5]],
  [#align(center)[1/4]], [#align(right)[50]], [#align(left)[Emberpod]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/4]], [#align(right)[50]], [#align(left)[Grinning Gourd]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/4]], [#align(right)[50]], [#align(left)[Maize Sentinel]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/4]], [#align(right)[50]], [#align(left)[Snaproot]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/4]], [#align(right)[50]], [#align(left)[Speartip Row]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/4]], [#align(right)[50]], [#align(left)[Thistleheart Cabbage]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/4]], [#align(right)[50]], [#align(left)[Wardbulb]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/2]], [#align(right)[100]], [#align(left)[Blightspud]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/2]], [#align(right)[100]], [#align(left)[Bloodvine Tomato]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/2]], [#align(right)[100]], [#align(left)[Numbknot]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/2]], [#align(right)[100]], [#align(left)[Podswarm]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1/2]], [#align(right)[100]], [#align(left)[Pruneling]], [#align(left)[Fey]], [#align(left)[Ch. 6]],
  [#align(center)[1]], [#align(right)[200]], [#align(left)[Animated Hoe]], [#align(left)[Construct]], [#align(left)[Ch. 6]],
  [#align(center)[1]], [#align(right)[200]], [#align(left)[Animated Shears]], [#align(left)[Construct]], [#align(left)[Ch. 6]],
  [#align(center)[1]], [#align(right)[200]], [#align(left)[Animated Spade]], [#align(left)[Construct]], [#align(left)[Ch. 6]],
  [#align(center)[1]], [#align(right)[200]], [#align(left)[Animated Watering Can]], [#align(left)[Construct]], [#align(left)[Ch. 6]],
  [#align(center)[1]], [#align(right)[200]], [#align(left)[Bindweed Creeper]], [#align(left)[Plant]], [#align(left)[Ch. 5]],
  [#align(center)[1]], [#align(right)[200]], [#align(left)[Chimeweed]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1]], [#align(right)[200]], [#align(left)[Rollrind]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[1]], [#align(right)[200]], [#align(left)[The Runt Patch]], [#align(left)[Plant]], [#align(left)[Ch. 2]],
  [#align(center)[2]], [#align(right)[450]], [#align(left)[Animated Scythe]], [#align(left)[Construct]], [#align(left)[Ch. 6]],
  [#align(center)[2]], [#align(right)[450]], [#align(left)[Sting-Choir]], [#align(left)[Beast]], [#align(left)[Ch. 5]],
  [#align(center)[2]], [#align(right)[450]], [#align(left)[Tearmonger]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[2]], [#align(right)[450]], [#align(left)[Tithe-Crow]], [#align(left)[Fey]], [#align(left)[Ch. 6]],
  [#align(center)[3]], [#align(right)[700]], [#align(left)[Animated Hose]], [#align(left)[Construct]], [#align(left)[Ch. 6]],
  [#align(center)[3]], [#align(right)[700]], [#align(left)[Compost Shambler]], [#align(left)[Ooze]], [#align(left)[Ch. 5]],
  [#align(center)[3]], [#align(right)[700]], [#align(left)[Gourdstalker]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[3]], [#align(right)[700]], [#align(left)[Pikeling]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[3]], [#align(right)[700]], [#align(left)[Stalkstrider]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[3]], [#align(right)[700]], [#align(left)[Tumblewrack]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[4]], [#align(right)[1,100]], [#align(left)[Bramblehead]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
)

#table(
  columns: 5,
  inset: (x: 3pt, y: 2.4pt),
  stroke: (x, y) => (bottom: 0.5pt + rule-col),
  table.header(align(center)[#label-head("CR")], align(right)[#label-head("XP")], align(left)[#label-head("Creature")], align(left)[#label-head("Type")], align(left)[#label-head("Ch.")]),
  [#align(center)[4]], [#align(right)[1,100]], [#align(left)[Censerhead]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[4]], [#align(right)[1,100]], [#align(left)[Drownbulb]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[4]], [#align(right)[1,100]], [#align(left)[Gravegourd]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[4]], [#align(right)[1,100]], [#align(left)[Rookery Choir]], [#align(left)[Fey]], [#align(left)[Ch. 6]],
  [#align(center)[4]], [#align(right)[1,100]], [#align(left)[Rootlance]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[4]], [#align(right)[1,100]], [#align(left)[Shellmaw]], [#align(left)[Monstrosity]], [#align(left)[Ch. 5]],
  [#align(center)[4]], [#align(right)[1,100]], [#align(left)[Vinelasher]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[5]], [#align(right)[1,800]], [#align(left)[Fondvine]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[5]], [#align(right)[1,800]], [#align(left)[Gingerling]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[5]], [#align(right)[1,800]], [#align(left)[Hollowman]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[5]], [#align(right)[1,800]], [#align(left)[Tanglepod]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[5]], [#align(right)[1,800]], [#align(left)[The Scarecrow]], [#align(left)[Construct]], [#align(left)[Ch. 5]],
  [#align(center)[5]], [#align(right)[1,800]], [#align(left)[The Under-Gardener]], [#align(left)[Fey]], [#align(left)[Ch. 6]],
  [#align(center)[6]], [#align(right)[2,300]], [#align(left)[Scorchvine]], [#align(left)[Plant]], [#align(left)[Ch. 3]],
  [#align(center)[6]], [#align(right)[2,300]], [#align(left)[Shearbeetle]], [#align(left)[Beast]], [#align(left)[Ch. 5]],
  [#align(center)[7]], [#align(right)[2,900]], [#align(left)[Blight Mother]], [#align(left)[Plant]], [#align(left)[Ch. 5]],
  [#align(center)[7]], [#align(right)[2,900]], [#align(left)[Hive-Warden]], [#align(left)[Monstrosity]], [#align(left)[Ch. 5]],
  [#align(center)[7]], [#align(right)[2,900]], [#align(left)[The Wick]], [#align(left)[Construct]], [#align(left)[Ch. 5]],
  [#align(center)[8]], [#align(right)[3,900]], [#align(left)[The Gardener]], [#align(left)[Fey]], [#align(left)[Ch. 6]],
  [#align(center)[9]], [#align(right)[5,000]], [#align(left)[Gallows Rook]], [#align(left)[Fey]], [#align(left)[Ch. 6]],
  [#align(center)[9]], [#align(right)[5,000]], [#align(left)[The Lachrymose]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[10]], [#align(right)[5,900]], [#align(left)[The Thistle Colossus]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[11]], [#align(right)[7,200]], [#align(left)[Deepspire]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[11]], [#align(right)[7,200]], [#align(left)[The Harvest Crown]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[12]], [#align(right)[8,400]], [#align(left)[The Bloodvine Sovereign]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[12]], [#align(right)[8,400]], [#align(left)[The Reliquary]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[13]], [#align(right)[10,000]], [#align(left)[The Serried Crown]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[13]], [#align(right)[10,000]], [#align(left)[Torpor]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[14]], [#align(right)[11,500]], [#align(left)[The Pumpkin King]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[15]], [#align(right)[13,000]], [#align(left)[The Scald]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[16]], [#align(right)[15,000]], [#align(left)[The Green Multitude]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[16]], [#align(right)[15,000]], [#align(left)[The Long Root]], [#align(left)[Plant]], [#align(left)[Ch. 4]],
  [#align(center)[22]], [#align(right)[41,000]], [#align(left)[The Perennial]], [#align(left)[Plant]], [#align(left)[Ch. 7]],
)
]

#section("Index by species")[
The ten cultivated species, each across all three stages. The number after each creature is its challenge rating.

#table(
  columns: 4,
  inset: (x: 3pt, y: 2.4pt),
  stroke: (x, y) => (bottom: 0.5pt + rule-col),
  table.header(align(left)[#label-head("Species")], align(left)[#label-head("Stage 1")], align(left)[#label-head("Stage 2")], align(left)[#label-head("Stage 3")]),
  [#align(left)[Pumpkin]], [#align(left)[Grinning Gourd (1/4)]], [#align(left)[Gourdstalker (3)]], [#align(left)[Pumpkin King (14)]],
  [#align(left)[Onion]], [#align(left)[Weeping Onion (1/8)]], [#align(left)[Tearmonger (2)]], [#align(left)[Lachrymose (9)]],
  [#align(left)[Maize]], [#align(left)[Maize Sentinel (1/4)]], [#align(left)[Stalkstrider (3)]], [#align(left)[Harvest Crown (11)]],
  [#align(left)[Cabbage]], [#align(left)[Thistleheart Cabbage (1/4)]], [#align(left)[Bramblehead (4)]], [#align(left)[Thistle Colossus (10)]],
  [#align(left)[Tomato]], [#align(left)[Bloodvine Tomato (1/2)]], [#align(left)[Vinelasher (4)]], [#align(left)[Bloodvine Sovereign (12)]],
  [#align(left)[Potato]], [#align(left)[Blightspud (1/2)]], [#align(left)[Hollowman (5)]], [#align(left)[Long Root (16)]],
  [#align(left)[Garlic]], [#align(left)[Wardbulb (1/4)]], [#align(left)[Censerhead (4)]], [#align(left)[Reliquary (12)]],
  [#align(left)[Chili]], [#align(left)[Emberpod (1/4)]], [#align(left)[Scorchvine (6)]], [#align(left)[Scald (15)]],
  [#align(left)[Asparagus]], [#align(left)[Speartip Row (1/4)]], [#align(left)[Pikeling (3)]], [#align(left)[Serried Crown (13)]],
  [#align(left)[Pea]], [#align(left)[Podswarm (1/2)]], [#align(left)[Tanglepod (5)]], [#align(left)[Green Multitude (16)]],
  [#align(left)[Carrot]], [#align(left)[Snaproot (1/4)]], [#align(left)[Rootlance (4)]], [#align(left)[Deepspire (11)]],
  [#align(left)[Ginger]], [#align(left)[Numbknot (1/2)]], [#align(left)[Gingerling (5)]], [#align(left)[Torpor (13)]],
)

*Variants* are their own creatures, not modifiers: Rollrind (1), Chimeweed (1), The Runt Patch (1), Drownbulb (4), Gravegourd (4), Fondvine (5), Tumblewrack (3). See _The Soil_ in Chapter 1 for which ground produces what.
]
