// Generated by scripts/generate-print.mjs from site/src/content/waking-garden/overview.mdx — do not edit.
// Chapter order and print-only pages live in print/waking-garden.typ.
#import "../lib.typ": *

#section("What's in each chapter")[
*Chapter 1* is the setting: how these plants grow, what makes them dangerous, and what a party can tell by looking at the dirt. It’s short, and it makes everything after it make sense. Read it first.

*Chapters 2–4* are the cultivated plants, arranged by stage of life. A plant does not change stage during a fight — it changes over seasons. Which stage a party meets is a fact about the _place_.

*Chapter 5* is everything else that lives in a garden. Weeds, pests, rot, and the things that keep them down. Several of these would rather eat a vegetable than a person.

*Chapter 6* is the answer to who has been doing all this on purpose.

*Chapter 7* is the answer to why any of it woke up in the first place.

*Appendix A* has nineteen ready-to-run encounters from level 1 to level 20, each with its terrain, its roster, and the concept it’s built around.
]

#subhead("Stage 1 and challenge rating")
A creature with Speed 0 is a hazard, not an encounter. Players will walk around it, and they’re right to. Every Stage 1 creature in Chapter 2 earns its listed challenge rating only when one of these is true:

- *Terrain forces contact.* A walled kitchen garden, a greenhouse, a hedge maze, furrows narrow enough that a 10-foot reach covers the path.
- *The plants are the objective.* The party needs them harvested, cleared, or taken alive.
- *They’re guarding something.* A Stage 1 patch around a cache is a cheap, patient alarm that never sleeps and can’t be bribed.
- *They’re supporting something mobile.* One #cref("c-stalkstrider", [Stalkstrider]) among four rooted Maize Sentinels is a better fight than either alone.

In open ground with no clock, halve their effective challenge rating. The ash-grown plants are the exception, because they move.
